image: Visual Studio 2017

install:
  - ps: Start-FileDownload https://www.rarlab.com/rar/UnRARDLL.exe C:/UnRARDLL.exe
  - 7z x C:/UnRARDLL.exe -oC:/UnRAR > NUL

before_build:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:STRING=../install -DUNRAR_ROOT:STRING=C:/UnRAR -DCMAKE_PREFIX_PATH:STRING=C:/Qt/5.11.1/msvc2017_64 -DCMAKE_GENERATOR_PLATFORM:STRING=x64 ..

build_script:
  - cmake --build .
  
after_build:
  - cmake --build . --target install
  
before_test:
  - cd ../install
  - mkdir C:/UnRarTest
  - ps: Start-FileDownload https://www.rarlab.com/rar/rarlng.rar C:/UnRarTest/test.rar

test_script:
  - ./RARStreamer --help
  - ./RARStreamer -o C:/UnRarTest/output C:/UnRarTest/test.rar