image: Visual Studio 2017

install:
  - ps: Start-FileDownload https://www.rarlab.com/rar/UnRARDLL.exe UnRARDLL.exe
  - 7z x UnRARDLL.exe -oUnRAR

before_build:
  - md build
  - cd build
  - cmake -DCMAKE_PREFIX_PATH:STRING=C:\Qt\5.11.1\msvc2017_64 -DCMAKE_GENERATOR_PLATFORM:STRING=x64 ..
