image: Visual Studio 2017

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - SET

install:
  - ps: Start-FileDownload https://www.rarlab.com/rar/UnRARDLL.exe C:\UnRARDLL.exe
  - 7z x C:\UnRARDLL.exe -oC:\UnRAR > NUL

before_build:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../install -DUNRAR_ROOT=C:/UnRAR -DCMAKE_PREFIX_PATH=C:/Qt/5.11.1/msvc2017_64 -DCMAKE_GENERATOR_PLATFORM=x64 ..

build_script:
  - cmake --build . --config Release -- /verbosity:minimal
  
after_build:
  - cmake --build . --config Release --target install -- /verbosity:minimal
  - cd ..\install\
  - C:\Qt\5.11.1\msvc2017_64\bin\windeployqt.exe --release bin\RARStreamer.exe --verbose 1
  - mkdir RARStreamer
  - ps: Copy-Item bin\Qt5Gui.dll        -Destination RARStreamer\
  - ps: Copy-Item bin\Qt5Core.dll       -Destination RARStreamer\
  - ps: Copy-Item bin\Qt5Widgets.dll    -Destination RARStreamer\
  - ps: Copy-Item bin\platforms         -Destination RARStreamer\ -Recurse
  - ps: Copy-Item bin\styles            -Destination RARStreamer\ -Recurse
  - ps: Copy-Item bin\UnRAR64.dll       -Destination RARStreamer\
  - ps: Copy-Item bin\RARStreamer.exe   -Destination RARStreamer\
  - ps: Copy-Item bin\USED_LICENSES.txt -Destination RARStreamer\
  - ps: Copy-Item bin\LICENSE           -Destination RARStreamer\LICENSE.txt
  - ps: Copy-Item bin\LICENSE.rtf       -Destination RARStreamer\
  - ps: Copy-Item C:\UnRAR\license.txt  -Destination RARStreamer\USED_LICENSE_UNRAR.txt
  - 7z a RARStreamer.7z RARStreamer
  - C:\PROGRA~2\WIXTOO~1.11\bin\candle.exe RARStreamerInstaller.wxs
  - C:\PROGRA~2\WIXTOO~1.11\bin\light.exe -ext WixUIExtension RARStreamerInstaller.wixobj
  
test: off

artifacts:
  - path: 'install\RARStreamer.7z'  # relative to repo root
    name: RARStreamer
  - path: 'install\RARStreamerInstaller.msi'  # relative to repo root
    name: RARStreamerInstaller
    
deploy:
  release: RARStreamer-v$(appveyor_build_version)
  description: 'RARStreamer Installer'
  provider: GitHub
  auth_token:
    secure: qsIWcINGZGs+ToSD6GwqPTdVh+H2zlr5e5x+BvxQAubIpqAmGYy/TMj6S/f5niq3 # your encrypted token from GitHub
  artifact: 'install\RARStreamerInstaller.msi'        
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only