image: Visual Studio 2017

install:
  - ps: Start-FileDownload https://www.rarlab.com/rar/UnRARDLL.exe C:\UnRARDLL.exe
  - 7z x C:\UnRARDLL.exe -oC:\UnRAR > NUL

before_build:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DUNRAR_ROOT=C:/UnRAR -DCMAKE_PREFIX_PATH=C:/Qt/5.11.1/msvc2017_64 -DCMAKE_GENERATOR_PLATFORM=x64 ..

build_script:
  - cmake --build .
  
after_build:
  - cmake --build . --target install
  - cd ..\install\
  - C:\Qt\5.11.1\msvc2017_64\bin\windeployqt.exe --release bin\RARStreamer.exe
  - mkdir RARStreamer
  - ps: Copy-Item bin\Qt5Core.dll, bin\Qt5Gui.dll, bin\Qt5Widgets.dll -Destination RARStreamer\
  - ps: Copy-Item bin\UnRAR64.dll -Destination RARStreamer\
  - ps: Copy-Item bin\platforms -Destination RARStreamer\platforms
  - 7z a RARStreamer.7z RARStreamer
  
test: off

artifacts:
  - path: 'install\RARStreamer.7z'  # relative to repo root
    name: RARStreamer