image: Visual Studio 2017

install:
  - ps: Start-FileDownload https://www.rarlab.com/rar/UnRARDLL.exe C:\UnRARDLL.exe
  - 7z x C:\UnRARDLL.exe -oC:\UnRAR > NUL

before_build:
  - mkdir build
  - cd build
  - dir C:\UnRAR
  - dir C:\UnRAR\x64
  - cmake -DCMAKE_INSTALL_PREFIX:STRING=..\install -DUNRAR_ROOT:STRING=C:\UnRAR -DCMAKE_PREFIX_PATH:STRING=C:\Qt\5.11.1\msvc2017_64 -DCMAKE_GENERATOR_PLATFORM:STRING=x64 ..

build_script:
  - cmake make
  
after_build:
  - cmake make install