version: 2.1

executors:
    linux:
        docker:
            - image: circleci/buildpack-deps:bionic

jobs:
    build-unrar:
        executor: linux
        steps:
            - run: git clone git@github.com:pmachapman/unrar.git
            - run:
                command: make lib
                working_directory: unrar

            - persist_to_workspace:
                root: .
                paths:
                    - unrar/dll.hpp
                    - unrar/libunrar.a

workflows:
    version: 2.1
    build:
        jobs:
            - build-unrar
