version: 2.1

executors:
    linux:
        docker:
            - image: circleci/buildpack-deps:bionic

jobs:
    build-unrar:
        executor: linux
        steps:
            - run: git clone https://github.com/pmachapman/unrar.git
            - run:
                command: make lib
                working_directory: unrar

            - persist_to_workspace:
                root: .
                paths:
                    - unrar/dll.hpp
                    - unrar/libunrar.a

    build-rarstreamer:
        executor: linux
        steps:
            - checkout
            - attach_workspace:
                at: /tmp/workspace
            - run: mkdir build
            - run:
                command: cmake -DUNRAR_ROOT=/tmp/workspace/unrar ..
                working_directory: unrar

workflows:
    version: 2.1
    build:
        jobs:
            - build-unrar
            - build-rarstreamer:
                requires:
                    - build-unrar
